app = "vk-poster-app" # Вы можете поменять это на свое уникальное имя
primary_region = "ams" # Амстердам, как пример

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
