services:
  - type: web
    name: vk-matrix-poster
    env: python
    plan: free
    buildCommand: "python -m pip install -r requirements.txt"
    startCommand: "python -m gunicorn --bind 0.0.0.0:$PORT app:app"
